const $=id=>document.getElementById(id);const state=JSON.parse(localStorage.getItem('clr2')||'null')||{cash:3900,rep:70,wins:8,losses:5,gear:3.55,shift:5200};let race={},ctx,cv,W,H,lastFrame=0;
function persist(){localStorage.setItem('clr2',JSON.stringify(state))}function sync(){cash.textContent=state.cash;repTop.textContent=state.rep;rep.textContent=state.rep;wins.textContent=state.wins;losses.textContent=state.losses;prog.value=state.rep%100;gear.value=state.gear;gearText.textContent=state.gear.toFixed(2);shift.value=state.shift;shiftText.textContent=state.shift+' RPM'}
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));scrollTo(0,0);if(id==='race'){resizeRace();resetRace()}if(id==='garage')drawGarage()}
function saveTune(){state.gear=+gear.value;state.shift=+shift.value;persist();sync();go('garage')}gear.oninput=()=>gearText.textContent=(+gear.value).toFixed(2);shift.oninput=()=>shiftText.textContent=shift.value+' RPM';
function resizeRace(){cv=$('raceCanvas');const r=cv.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);cv.width=r.width*d;cv.height=r.height*d;ctx=cv.getContext('2d');ctx.setTransform(d,0,0,d,0,0);W=r.width;H=r.height;drawRace(performance.now())}
function roadX(y,side){const horizon=H*.29,t=(y-horizon)/(H-horizon),half=34+t*W*.46;return W/2+(side?half:-half)}
function drawTruck(c,x,y,s,player,wheelSpin=0){c.save();c.translate(x,y);c.scale(s,s);const body=player?'#151a1b':'#22282a',edge=player?'#4c5757':'#4b5557';c.fillStyle='#050606';c.beginPath();c.ellipse(-38,4,18,27,0,0,Math.PI*2);c.ellipse(38,4,18,27,0,0,Math.PI*2);c.fill();c.fillStyle='#222';c.beginPath();c.arc(-38,5,10,0,Math.PI*2);c.arc(38,5,10,0,Math.PI*2);c.fill();c.fillStyle=body;c.strokeStyle=edge;c.lineWidth=2;c.beginPath();c.moveTo(-48,-18);c.lineTo(-42,-55);c.lineTo(-27,-78);c.lineTo(27,-78);c.lineTo(42,-55);c.lineTo(48,-18);c.lineTo(46,12);c.lineTo(-46,12);c.closePath();c.fill();c.stroke();c.fillStyle='#091114';c.beginPath();c.moveTo(-25,-70);c.lineTo(25,-70);c.lineTo(34,-50);c.lineTo(-34,-50);c.closePath();c.fill();c.strokeStyle='#334247';c.stroke();c.fillStyle='#0d1112';c.fillRect(-42,-45,84,33);c.strokeStyle='#3c4546';c.strokeRect(-42,-45,84,33);c.fillStyle='#a51b17';c.fillRect(-39,-37,13,10);c.fillRect(26,-37,13,10);c.shadowBlur=10;c.shadowColor='#e22';c.fillRect(-38,-36,10,8);c.fillRect(28,-36,10,8);c.shadowBlur=0;if(player){c.fillStyle='#8dff00';c.fillRect(-39,-10,78,4);c.font='italic bold 11px Arial';c.textAlign='center';c.fillText('R/T',0,-20)}else{c.fillStyle='#707778';c.font='bold 8px Arial';c.textAlign='center';c.fillText('OUTRIDER',0,-20)}c.fillStyle='#090a0a';c.fillRect(-24,7,48,6);c.restore()}
function drawSceneBase(c,scroll){const horizon=H*.29;let g=c.createLinearGradient(0,0,0,horizon);g.addColorStop(0,'#030a11');g.addColorStop(1,'#101a1c');c.fillStyle=g;c.fillRect(0,0,W,horizon);c.fillStyle='#e7e8df';c.beginPath();c.arc(W*.82,H*.12,18,0,Math.PI*2);c.fill();c.shadowColor='#fff';c.shadowBlur=18;c.fill();c.shadowBlur=0;c.fillStyle='#071008';c.beginPath();c.moveTo(0,horizon);for(let x=0;x<=W;x+=24)c.lineTo(x,horizon-15-(Math.sin(x*.13)*8+Math.sin(x*.037)*13));c.lineTo(W,horizon+20);c.lineTo(0,horizon+20);c.fill();c.fillStyle='#0b100d';c.fillRect(0,horizon,W,H-horizon);c.fillStyle='#353738';c.beginPath();c.moveTo(roadX(horizon,0),horizon);c.lineTo(roadX(horizon,1),horizon);c.lineTo(roadX(H,1),H);c.lineTo(roadX(H,0),H);c.closePath();c.fill();c.strokeStyle='#deded7';c.lineWidth=3;c.beginPath();c.moveTo(roadX(horizon,0)+4,horizon);c.lineTo(roadX(H,0)+4,H);c.moveTo(roadX(horizon,1)-4,horizon);c.lineTo(roadX(H,1)-4,H);c.stroke();for(let i=0;i<16;i++){let z=((i*52-scroll)%832+832)%832;let p=z/832,y=horizon+Math.pow(p,1.65)*(H-horizon);let w=2+p*8,h=5+p*30;c.fillStyle='#deded6';c.fillRect(W/2-w/2,y,w,h)}for(let i=0;i<26;i++){let z=((i*37-scroll*1.4)%962+962)%962,p=z/962,y=horizon+Math.pow(p,1.6)*(H-horizon);c.strokeStyle=`rgba(255,255,255,${.015+p*.035})`;c.lineWidth=1+p*2;c.beginPath();c.moveTo(roadX(y,0)+12,y);c.lineTo(roadX(y,1)-12,y);c.stroke()}}
function drawFinish(c,remaining){if(remaining>300)return;const p=1-Math.max(0,remaining)/300,y=H*.31+Math.pow(p,1.7)*H*.64,l=roadX(y,0),r=roadX(y,1);c.save();c.strokeStyle='#f2f1e8';c.lineWidth=4+10*p;c.beginPath();c.moveTo(l,y);c.lineTo(r,y);c.stroke();if(p>.3){const n=12,w=(r-l)/n;c.fillStyle='#111';for(let i=0;i<n;i+=2)c.fillRect(l+i*w,y-(2+5*p),w,4+10*p)}c.restore()}
function drawFlagger(c){const x=W*.14,y=H*.79;c.strokeStyle='#111';c.lineWidth=10;c.lineCap='round';c.beginPath();c.moveTo(x,y-32);c.lineTo(x,y+13);c.stroke();c.fillStyle='#c99678';c.beginPath();c.arc(x,y-47,10,0,Math.PI*2);c.fill();c.strokeStyle='#161616';c.lineWidth=7;c.beginPath();c.moveTo(x-3,y-24);c.lineTo(x-18,y-5);c.moveTo(x+3,y-24);c.lineTo(x+20,y-35);c.stroke()}
function drawRace(now){if(!ctx)return;ctx.clearRect(0,0,W,H);drawSceneBase(ctx,race.dist*5);drawFinish(ctx,660-race.dist);const startY=H*.84;if((race.phase==='burnout'||race.phase==='stage'||race.phase==='waiting'||race.phase==='green')){ctx.strokeStyle='#f0eee5';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(roadX(startY,0)+8,startY);ctx.lineTo(roadX(startY,1)-8,startY);ctx.stroke();drawFlagger(ctx)}let py=H*.80,px=W*.63;drawTruck(ctx,px,py,1.05,true,race.dist);let elapsed=race.start?(now-race.start)/1000:0,od=race.oppDist||0,lead=od-race.dist;let oy=H*.58-Math.max(-65,Math.min(80,lead*.7));let os=.68-Math.max(-.12,Math.min(.12,lead*.0012));drawTruck(ctx,W*.39,oy,os,false,od);if(race.phase==='burnout'&&race.burning){for(let i=0;i<9;i++){ctx.fillStyle=`rgba(210,215,212,${.07+i*.012})`;ctx.beginPath();ctx.arc(px-35+(i%3)*30,py+12-(i*7)%35,18+(i%4)*7,0,Math.PI*2);ctx.fill()}}}
function setDash(){raceRpm.textContent=Math.round(race.rpm);raceGear.textContent=race.gear;raceSpeed.textContent=Math.round(race.speed);raceDist.textContent=Math.min(660,Math.round(race.dist));distanceBoard.textContent=(race.phase==='done'?'FINISH':race.phase==='running'?'RACING':'START')+' • '+Math.min(660,Math.round(race.dist))+' / 660 FT';tachFill.style.width=Math.min(100,Math.max(3,(race.rpm-800)/5400*100))+'%'}
function resetRace(){cancelAnimationFrame(race.raf);clearInterval(race.burnTimer);race={phase:'burnout',rpm:1100,gear:1,speed:0,dist:0,oppDist:0,start:0,last:0,burnout:0,burning:false,spin:0,rt:null,greenAt:0,shiftPenalty:0,oppEt:9.75+(Math.random()-.5)*.5};stageDot.classList.remove('on');flash.classList.remove('on');raceBtn.classList.remove('hidden');shiftBtn.classList.add('hidden');raceBtn.disabled=false;raceBtn.textContent='HOLD BURNOUT';raceMsg.textContent='HOLD BURNOUT • BUILD TIRE HEAT';tireHeat.style.width='0%';slip.classList.add('hidden');setDash();drawRace(performance.now())}
function burnOn(e){if(e)e.preventDefault();if(race.phase!=='burnout'||race.burning)return;race.burning=true;race.rpm=4700;raceMsg.textContent='BURNOUT • HEATING THE RADIALS';race.burnTimer=setInterval(()=>{race.burnout=Math.min(100,race.burnout+2);tireHeat.style.width=race.burnout+'%';drawRace(performance.now())},60);setDash()}
function burnOff(e){if(e)e.preventDefault();if(race.phase!=='burnout'||!race.burning)return;clearInterval(race.burnTimer);race.burnTimer=0;race.burning=false;race.rpm=1100;race.phase='stage';raceBtn.textContent='ROLL INTO STAGE';raceMsg.textContent=race.burnout>=45?'BURNOUT GOOD • CREEP TO THE PAINT':'TIRES COOL • EXPECT WHEELSPIN';setDash();drawRace(performance.now())}
function stage(){race.phase='waiting';raceBtn.textContent='STAGED';raceBtn.disabled=true;stageDot.classList.add('on');raceMsg.textContent='STAGED • WATCH THE FLASHLIGHT';setTimeout(()=>{if(race.phase!=='waiting')return;flash.classList.add('on');race.greenAt=performance.now();race.phase='green';raceBtn.disabled=false;raceBtn.textContent='LAUNCH';raceMsg.textContent='GO!';setTimeout(()=>flash.classList.remove('on'),400)},900+Math.random()*1500)}
function launch(){let now=performance.now();race.rt=race.phase==='waiting'?-0.001:(now-race.greenAt)/1000;race.phase='running';race.start=now;race.last=now;race.rpm=2700;race.spin=Math.max(0,35-race.burnout*.33)+(state.gear-3.55)*14;raceBtn.classList.add('hidden');shiftBtn.classList.remove('hidden');raceMsg.textContent=race.rt<0?'RED LIGHT!':'DIG!';race.raf=requestAnimationFrame(tick)}
const ratios=[2.45,1.45,1,.69];function shiftGear(){if(race.phase!=='running'||race.gear>=4)return;let d=Math.abs(race.rpm-state.shift);race.shiftPenalty+=d/1900;race.gear++;race.rpm=Math.max(2400,race.rpm*(ratios[race.gear-1]/ratios[race.gear-2]));raceMsg.textContent=d<300?'CLEAN SHIFT!':race.rpm>state.shift?'LATE SHIFT':'SHIFT';setDash()}
function tick(now){if(race.phase!=='running')return;let dt=Math.min(.04,(now-race.last)/1000);race.last=now;let traction=1-Math.min(.42,race.spin/100),ratio=ratios[race.gear-1]*state.gear,acc=(245/3850*1150*ratio/8.8)*traction/(1+race.speed/105);race.speed+=Math.max(2.5,acc-race.shiftPenalty*.65)*dt;race.dist+=race.speed*1.46667*dt;race.rpm=800+race.speed*state.gear*ratios[race.gear-1]*336/28;race.rpm=Math.min(6250,race.rpm);race.spin=Math.max(0,race.spin-dt*18);let elapsed=(now-race.start)/1000;race.oppDist=Math.min(660,660*Math.pow(Math.min(1,elapsed/race.oppEt),1.15));setDash();drawRace(now);if(race.dist>=660)return finish(now);race.raf=requestAnimationFrame(tick)}
function finish(now){race.phase='done';shiftBtn.classList.add('hidden');raceBtn.classList.remove('hidden');raceBtn.textContent='RACE AGAIN';let et=(now-race.start)/1000+race.shiftPenalty*.12,mph=race.speed,win=race.rt>=0&&et<race.oppEt;if(win){state.cash+=200;state.wins++;state.rep+=10}else{state.cash=Math.max(0,state.cash-200);state.losses++}persist();sync();raceMsg.textContent=race.rt<0?'RED LIGHT • JAX TAKES IT':win?'WIN LIGHT • RACIN’ CAJUN!':'JAX GOT YOU';slip.innerHTML=`<div class="winner">${win?'YOU WIN':'YOU LOSE'}</div><h3>1/8 MILE TIME SLIP</h3><div class="slipgrid"><span>REACTION<b>${race.rt<0?'RED':race.rt.toFixed(3)}</b></span><span>YOUR ET<b>${et.toFixed(3)}</b></span><span>YOUR MPH<b>${mph.toFixed(1)}</b></span><span>JAX ET<b>${race.oppEt.toFixed(3)}</b></span></div>`;slip.classList.remove('hidden');drawRace(now)}
raceBtn.addEventListener('pointerdown',e=>{if(race.phase==='burnout')burnOn(e)});raceBtn.addEventListener('pointerup',e=>{if(race.phase==='burnout')burnOff(e)});raceBtn.addEventListener('pointercancel',e=>{if(race.phase==='burnout')burnOff(e)});raceBtn.addEventListener('click',()=>{if(race.phase==='stage')stage();else if(race.phase==='waiting'||race.phase==='green')launch();else if(race.phase==='done')resetRace()});shiftBtn.onclick=shiftGear;
function drawGarage(){let c=$('garageCanvas'),r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);c.width=r.width*d;c.height=r.height*d;let x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,r.width,r.height);x.fillStyle='#202323';x.fillRect(0,r.height*.63,r.width,r.height*.37);x.save();x.translate(r.width/2,r.height*.78);x.scale(1.8,1.8);drawTruck(x,0,0,1,true);x.restore()}
addEventListener('resize',()=>{if(race.classList?.contains)return;if($('race').classList.contains('active'))resizeRace()});sync();go('home');
