const state=JSON.parse(localStorage.getItem('clr01'))||{cash:2500,wins:0,losses:0,rep:0,gear:3.55,shift:5200};
let race={phase:'idle',rpm:900,gear:1,speed:0,dist:0,start:0,last:0,rt:null,greenAt:0,launched:false,shiftPenalty:0,spin:0,burnout:0,raf:0,finished:false};
const ratios=[2.45,1.45,1.00,0.69];
function sync(){cash.textContent=state.cash;wins.textContent=state.wins;losses.textContent=state.losses;rep.textContent=rep2.textContent=state.rep;prog.value=state.rep;gear.value=state.gear;gearText.textContent=gearText2.textContent=state.gear.toFixed(2);shift.value=state.shift;shiftVal.textContent=state.shift+' RPM'}
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('navActive',b.dataset.screen===id));scrollTo(0,0)}
function updateGear(v){const n=(+v).toFixed(2);gearText.textContent=n;gearText2.textContent=n}
function saveTune(){state.gear=+gear.value;state.shift=+shift.value;localStorage.setItem('clr01',JSON.stringify(state));sync();go('garage')}
function setDash(){raceRpm.textContent=Math.round(race.rpm);raceGear.textContent=race.gear;raceSpeed.textContent=Math.round(race.speed);raceDist.textContent=Math.min(660,Math.round(race.dist));tachFill.style.width=Math.min(100,Math.max(0,(race.rpm-800)/5600*100))+'%'}
function resetRace(){cancelAnimationFrame(race.raf);race={phase:'burnout',rpm:1100,gear:1,speed:0,dist:0,start:0,last:0,rt:null,greenAt:0,launched:false,shiftPenalty:0,spin:0,burnout:0,raf:0,finished:false};slip.classList.add('hidden');raceTruck.style.left='10%';raceTruck.classList.remove('launching','spinning');stageLamp.classList.remove('on');flashLamp.classList.remove('on');raceMsg.textContent='HOLD BURNOUT TO HEAT THE TIRES';raceBtn.textContent='HOLD BURNOUT';raceBtn.disabled=false;raceBtn.classList.remove('hidden');shiftBtn.classList.add('hidden');setDash()}
function burnoutOn(){if(race.phase!=='burnout')return;race.rpm=4800;raceBtn.classList.add('pressed');raceMsg.textContent='BURNOUT • BUILDING TIRE HEAT';race.burnTimer=setInterval(()=>{race.burnout=Math.min(100,race.burnout+3);tireHeat.style.width=race.burnout+'%'},80);setDash()}
function burnoutOff(){if(race.phase!=='burnout')return;clearInterval(race.burnTimer);raceBtn.classList.remove('pressed');race.rpm=1100;race.phase='stage';raceBtn.textContent='ROLL INTO STAGE';raceMsg.textContent=race.burnout>45?'BURNOUT GOOD • ROLL TO THE LINE':'TIRES ARE COOL • ROLL TO THE LINE';setDash()}
function stage(){if(race.phase!=='stage')return;race.phase='waiting';raceBtn.disabled=true;raceBtn.textContent='STAGED';stageLamp.classList.add('on');raceTruck.style.left='17%';raceMsg.textContent='STAGED • WATCH THE FLASHLIGHT';const delay=1100+Math.random()*1900;setTimeout(()=>{if(race.phase!=='waiting')return;flashLamp.classList.add('on');race.greenAt=performance.now();race.phase='green';raceBtn.disabled=false;raceBtn.textContent='LAUNCH';raceMsg.textContent='GO!';setTimeout(()=>flashLamp.classList.remove('on'),450)},delay)}
function launch(){if(!['waiting','green'].includes(race.phase))return;const now=performance.now();race.rt=race.phase==='waiting'?-(race.greenAt||now)-1:(now-race.greenAt)/1000;if(race.phase==='waiting'){race.rt=-0.001;raceMsg.textContent='RED LIGHT!';}race.phase='running';race.launched=true;race.start=now;race.last=now;raceBtn.classList.add('hidden');shiftBtn.classList.remove('hidden');race.rpm=2600;race.spin=Math.max(0,35-race.burnout*.32)+(state.gear-3.55)*14;raceTruck.classList.add('launching');race.raf=requestAnimationFrame(tick)}
function shiftGear(){if(race.phase!=='running'||race.gear>=4)return;const diff=Math.abs(race.rpm-state.shift);race.shiftPenalty+=diff/2200;race.gear++;race.rpm=Math.max(2600,race.rpm*(ratios[race.gear-1]/ratios[race.gear-2]));raceMsg.textContent=diff<350?'CLEAN SHIFT!':race.rpm>state.shift?'LATE SHIFT':'EARLY SHIFT';setDash()}
function tick(now){if(race.phase!=='running')return;const dt=Math.min(.04,(now-race.last)/1000);race.last=now;const traction=1-Math.min(.38,race.spin/100);const power=245/3850;const ratio=ratios[race.gear-1]*state.gear;let accel=(power*1050*ratio/8.7)*traction/(1+race.speed/105);accel=Math.max(3,accel-race.shiftPenalty*.8);race.speed+=accel*dt;race.dist+=race.speed*1.46667*dt;race.rpm=800+(race.speed*state.gear*ratios[race.gear-1]*336/27.99);if(race.rpm>6200){race.rpm=6200;race.shiftPenalty+=.012}race.spin=Math.max(0,race.spin-dt*18);raceTruck.classList.toggle('spinning',race.spin>12);raceTruck.style.left=(17+Math.min(65,race.dist/660*65))+'%';setDash();if(race.dist>=660){finishRace(now);return}race.raf=requestAnimationFrame(tick)}
function finishRace(now){race.phase='done';race.finished=true;shiftBtn.classList.add('hidden');raceBtn.classList.remove('hidden');raceBtn.disabled=false;raceBtn.textContent='RACE AGAIN';raceBtn.onclick=resetRace;const raw=(now-race.start)/1000;const et=+(raw+race.shiftPenalty*.16).toFixed(3);const mph=+race.speed.toFixed(1);const rt=race.rt===null?0:race.rt;const opp=+(14.45+(Math.random()-.5)*.55).toFixed(3);const red=rt<0;const win=!red&&et<opp;if(win){state.cash+=200;state.wins++;state.rep+=10}else{state.cash=Math.max(0,state.cash-200);state.losses++}localStorage.setItem('clr01',JSON.stringify(state));sync();raceMsg.textContent=red?'RED LIGHT • LOSS':win?'WIN LIGHT!':'YOU GOT BEAT';slip.innerHTML=`<h3>1/8 MILE TIME SLIP</h3><div class="slipgrid"><span>REACTION<b>${red?'RED':rt.toFixed(3)}</b></span><span>ET<b>${et}</b></span><span>MPH<b>${mph}</b></span><span>OPPONENT<b>${opp}</b></span></div><small>${win?'+$200 • +10 REP':'-$200'}</small>`;slip.classList.remove('hidden')}
function raceAction(){if(race.phase==='idle'||race.phase==='done')resetRace();else if(race.phase==='stage')stage();else if(race.phase==='waiting'||race.phase==='green')launch()}
window.addEventListener('DOMContentLoaded',()=>{raceBtn.addEventListener('pointerdown',e=>{if(race.phase==='burnout'){e.preventDefault();burnoutOn()}});['pointerup','pointercancel','pointerleave'].forEach(ev=>raceBtn.addEventListener(ev,()=>{if(race.phase==='burnout')burnoutOff()}));resetRace();sync();go(document.querySelector('.screen.active')?.id||'home')});
